// <auto-generated />
namespace MyElearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class instructor_mig_up : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(instructor_mig_up));
        
        string IMigrationMetadata.Id
        {
            get { return "202310152144074_instructor_mig_up"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
